// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/shop-go/ent/goodssku"
	"github.com/a20070322/shop-go/ent/goodsspecsoption"
	"github.com/a20070322/shop-go/ent/goodsspu"
	"github.com/a20070322/shop-go/ent/predicate"
)

// GoodsSkuQuery is the builder for querying GoodsSku entities.
type GoodsSkuQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GoodsSku
	// eager-loading edges.
	withGoodsSpu         *GoodsSpuQuery
	withGoodsSpecsOption *GoodsSpecsOptionQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoodsSkuQuery builder.
func (gsq *GoodsSkuQuery) Where(ps ...predicate.GoodsSku) *GoodsSkuQuery {
	gsq.predicates = append(gsq.predicates, ps...)
	return gsq
}

// Limit adds a limit step to the query.
func (gsq *GoodsSkuQuery) Limit(limit int) *GoodsSkuQuery {
	gsq.limit = &limit
	return gsq
}

// Offset adds an offset step to the query.
func (gsq *GoodsSkuQuery) Offset(offset int) *GoodsSkuQuery {
	gsq.offset = &offset
	return gsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gsq *GoodsSkuQuery) Unique(unique bool) *GoodsSkuQuery {
	gsq.unique = &unique
	return gsq
}

// Order adds an order step to the query.
func (gsq *GoodsSkuQuery) Order(o ...OrderFunc) *GoodsSkuQuery {
	gsq.order = append(gsq.order, o...)
	return gsq
}

// QueryGoodsSpu chains the current query on the "goods_spu" edge.
func (gsq *GoodsSkuQuery) QueryGoodsSpu() *GoodsSpuQuery {
	query := &GoodsSpuQuery{config: gsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goodssku.Table, goodssku.FieldID, selector),
			sqlgraph.To(goodsspu.Table, goodsspu.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, goodssku.GoodsSpuTable, goodssku.GoodsSpuColumn),
		)
		fromU = sqlgraph.SetNeighbors(gsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGoodsSpecsOption chains the current query on the "goods_specs_option" edge.
func (gsq *GoodsSkuQuery) QueryGoodsSpecsOption() *GoodsSpecsOptionQuery {
	query := &GoodsSpecsOptionQuery{config: gsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goodssku.Table, goodssku.FieldID, selector),
			sqlgraph.To(goodsspecsoption.Table, goodsspecsoption.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, goodssku.GoodsSpecsOptionTable, goodssku.GoodsSpecsOptionPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(gsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GoodsSku entity from the query.
// Returns a *NotFoundError when no GoodsSku was found.
func (gsq *GoodsSkuQuery) First(ctx context.Context) (*GoodsSku, error) {
	nodes, err := gsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goodssku.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gsq *GoodsSkuQuery) FirstX(ctx context.Context) *GoodsSku {
	node, err := gsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoodsSku ID from the query.
// Returns a *NotFoundError when no GoodsSku ID was found.
func (gsq *GoodsSkuQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goodssku.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gsq *GoodsSkuQuery) FirstIDX(ctx context.Context) int {
	id, err := gsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoodsSku entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one GoodsSku entity is not found.
// Returns a *NotFoundError when no GoodsSku entities are found.
func (gsq *GoodsSkuQuery) Only(ctx context.Context) (*GoodsSku, error) {
	nodes, err := gsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goodssku.Label}
	default:
		return nil, &NotSingularError{goodssku.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gsq *GoodsSkuQuery) OnlyX(ctx context.Context) *GoodsSku {
	node, err := gsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoodsSku ID in the query.
// Returns a *NotSingularError when exactly one GoodsSku ID is not found.
// Returns a *NotFoundError when no entities are found.
func (gsq *GoodsSkuQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = &NotSingularError{goodssku.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gsq *GoodsSkuQuery) OnlyIDX(ctx context.Context) int {
	id, err := gsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoodsSkus.
func (gsq *GoodsSkuQuery) All(ctx context.Context) ([]*GoodsSku, error) {
	if err := gsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gsq *GoodsSkuQuery) AllX(ctx context.Context) []*GoodsSku {
	nodes, err := gsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoodsSku IDs.
func (gsq *GoodsSkuQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := gsq.Select(goodssku.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gsq *GoodsSkuQuery) IDsX(ctx context.Context) []int {
	ids, err := gsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gsq *GoodsSkuQuery) Count(ctx context.Context) (int, error) {
	if err := gsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gsq *GoodsSkuQuery) CountX(ctx context.Context) int {
	count, err := gsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gsq *GoodsSkuQuery) Exist(ctx context.Context) (bool, error) {
	if err := gsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gsq *GoodsSkuQuery) ExistX(ctx context.Context) bool {
	exist, err := gsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoodsSkuQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gsq *GoodsSkuQuery) Clone() *GoodsSkuQuery {
	if gsq == nil {
		return nil
	}
	return &GoodsSkuQuery{
		config:               gsq.config,
		limit:                gsq.limit,
		offset:               gsq.offset,
		order:                append([]OrderFunc{}, gsq.order...),
		predicates:           append([]predicate.GoodsSku{}, gsq.predicates...),
		withGoodsSpu:         gsq.withGoodsSpu.Clone(),
		withGoodsSpecsOption: gsq.withGoodsSpecsOption.Clone(),
		// clone intermediate query.
		sql:  gsq.sql.Clone(),
		path: gsq.path,
	}
}

// WithGoodsSpu tells the query-builder to eager-load the nodes that are connected to
// the "goods_spu" edge. The optional arguments are used to configure the query builder of the edge.
func (gsq *GoodsSkuQuery) WithGoodsSpu(opts ...func(*GoodsSpuQuery)) *GoodsSkuQuery {
	query := &GoodsSpuQuery{config: gsq.config}
	for _, opt := range opts {
		opt(query)
	}
	gsq.withGoodsSpu = query
	return gsq
}

// WithGoodsSpecsOption tells the query-builder to eager-load the nodes that are connected to
// the "goods_specs_option" edge. The optional arguments are used to configure the query builder of the edge.
func (gsq *GoodsSkuQuery) WithGoodsSpecsOption(opts ...func(*GoodsSpecsOptionQuery)) *GoodsSkuQuery {
	query := &GoodsSpecsOptionQuery{config: gsq.config}
	for _, opt := range opts {
		opt(query)
	}
	gsq.withGoodsSpecsOption = query
	return gsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoodsSku.Query().
//		GroupBy(goodssku.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gsq *GoodsSkuQuery) GroupBy(field string, fields ...string) *GoodsSkuGroupBy {
	group := &GoodsSkuGroupBy{config: gsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GoodsSku.Query().
//		Select(goodssku.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (gsq *GoodsSkuQuery) Select(field string, fields ...string) *GoodsSkuSelect {
	gsq.fields = append([]string{field}, fields...)
	return &GoodsSkuSelect{GoodsSkuQuery: gsq}
}

func (gsq *GoodsSkuQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gsq.fields {
		if !goodssku.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gsq.path != nil {
		prev, err := gsq.path(ctx)
		if err != nil {
			return err
		}
		gsq.sql = prev
	}
	return nil
}

func (gsq *GoodsSkuQuery) sqlAll(ctx context.Context) ([]*GoodsSku, error) {
	var (
		nodes       = []*GoodsSku{}
		withFKs     = gsq.withFKs
		_spec       = gsq.querySpec()
		loadedTypes = [2]bool{
			gsq.withGoodsSpu != nil,
			gsq.withGoodsSpecsOption != nil,
		}
	)
	if gsq.withGoodsSpu != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, goodssku.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &GoodsSku{config: gsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, gsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := gsq.withGoodsSpu; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*GoodsSku)
		for i := range nodes {
			if nodes[i].goods_spu_goods_sku == nil {
				continue
			}
			fk := *nodes[i].goods_spu_goods_sku
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(goodsspu.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "goods_spu_goods_sku" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.GoodsSpu = n
			}
		}
	}

	if query := gsq.withGoodsSpecsOption; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*GoodsSku, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.GoodsSpecsOption = []*GoodsSpecsOption{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*GoodsSku)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   goodssku.GoodsSpecsOptionTable,
				Columns: goodssku.GoodsSpecsOptionPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(goodssku.GoodsSpecsOptionPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{&sql.NullInt64{}, &sql.NullInt64{}}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, gsq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "goods_specs_option": %w`, err)
		}
		query.Where(goodsspecsoption.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "goods_specs_option" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.GoodsSpecsOption = append(nodes[i].Edges.GoodsSpecsOption, n)
			}
		}
	}

	return nodes, nil
}

func (gsq *GoodsSkuQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gsq.querySpec()
	return sqlgraph.CountNodes(ctx, gsq.driver, _spec)
}

func (gsq *GoodsSkuQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gsq *GoodsSkuQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   goodssku.Table,
			Columns: goodssku.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: goodssku.FieldID,
			},
		},
		From:   gsq.sql,
		Unique: true,
	}
	if unique := gsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goodssku.FieldID)
		for i := range fields {
			if fields[i] != goodssku.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gsq *GoodsSkuQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gsq.driver.Dialect())
	t1 := builder.Table(goodssku.Table)
	selector := builder.Select(t1.Columns(goodssku.Columns...)...).From(t1)
	if gsq.sql != nil {
		selector = gsq.sql
		selector.Select(selector.Columns(goodssku.Columns...)...)
	}
	for _, p := range gsq.predicates {
		p(selector)
	}
	for _, p := range gsq.order {
		p(selector)
	}
	if offset := gsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoodsSkuGroupBy is the group-by builder for GoodsSku entities.
type GoodsSkuGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gsgb *GoodsSkuGroupBy) Aggregate(fns ...AggregateFunc) *GoodsSkuGroupBy {
	gsgb.fns = append(gsgb.fns, fns...)
	return gsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gsgb *GoodsSkuGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gsgb.path(ctx)
	if err != nil {
		return err
	}
	gsgb.sql = query
	return gsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := gsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) StringsX(ctx context.Context) []string {
	v, err := gsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) StringX(ctx context.Context) string {
	v, err := gsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) IntsX(ctx context.Context) []int {
	v, err := gsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) IntX(ctx context.Context) int {
	v, err := gsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := gsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) Float64X(ctx context.Context) float64 {
	v, err := gsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := gsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GoodsSkuGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gsgb *GoodsSkuGroupBy) BoolX(ctx context.Context) bool {
	v, err := gsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gsgb *GoodsSkuGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gsgb.fields {
		if !goodssku.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gsgb *GoodsSkuGroupBy) sqlQuery() *sql.Selector {
	selector := gsgb.sql
	columns := make([]string, 0, len(gsgb.fields)+len(gsgb.fns))
	columns = append(columns, gsgb.fields...)
	for _, fn := range gsgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(gsgb.fields...)
}

// GoodsSkuSelect is the builder for selecting fields of GoodsSku entities.
type GoodsSkuSelect struct {
	*GoodsSkuQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gss *GoodsSkuSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gss.prepareQuery(ctx); err != nil {
		return err
	}
	gss.sql = gss.GoodsSkuQuery.sqlQuery(ctx)
	return gss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gss *GoodsSkuSelect) ScanX(ctx context.Context, v interface{}) {
	if err := gss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Strings(ctx context.Context) ([]string, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gss *GoodsSkuSelect) StringsX(ctx context.Context) []string {
	v, err := gss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gss *GoodsSkuSelect) StringX(ctx context.Context) string {
	v, err := gss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Ints(ctx context.Context) ([]int, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gss *GoodsSkuSelect) IntsX(ctx context.Context) []int {
	v, err := gss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gss *GoodsSkuSelect) IntX(ctx context.Context) int {
	v, err := gss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gss *GoodsSkuSelect) Float64sX(ctx context.Context) []float64 {
	v, err := gss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gss *GoodsSkuSelect) Float64X(ctx context.Context) float64 {
	v, err := gss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GoodsSkuSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gss *GoodsSkuSelect) BoolsX(ctx context.Context) []bool {
	v, err := gss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (gss *GoodsSkuSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodssku.Label}
	default:
		err = fmt.Errorf("ent: GoodsSkuSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gss *GoodsSkuSelect) BoolX(ctx context.Context) bool {
	v, err := gss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gss *GoodsSkuSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gss.sqlQuery().Query()
	if err := gss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gss *GoodsSkuSelect) sqlQuery() sql.Querier {
	selector := gss.sql
	selector.Select(selector.Columns(gss.fields...)...)
	return selector
}
