// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/shop-go/ent/goodsspecs"
	"github.com/a20070322/shop-go/ent/predicate"
)

// GoodsSpecsDelete is the builder for deleting a GoodsSpecs entity.
type GoodsSpecsDelete struct {
	config
	hooks    []Hook
	mutation *GoodsSpecsMutation
}

// Where adds a new predicate to the GoodsSpecsDelete builder.
func (gsd *GoodsSpecsDelete) Where(ps ...predicate.GoodsSpecs) *GoodsSpecsDelete {
	gsd.mutation.predicates = append(gsd.mutation.predicates, ps...)
	return gsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gsd *GoodsSpecsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gsd.hooks) == 0 {
		affected, err = gsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoodsSpecsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gsd.mutation = mutation
			affected, err = gsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gsd.hooks) - 1; i >= 0; i-- {
			mut = gsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gsd *GoodsSpecsDelete) ExecX(ctx context.Context) int {
	n, err := gsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gsd *GoodsSpecsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: goodsspecs.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: goodsspecs.FieldID,
			},
		},
	}
	if ps := gsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, gsd.driver, _spec)
}

// GoodsSpecsDeleteOne is the builder for deleting a single GoodsSpecs entity.
type GoodsSpecsDeleteOne struct {
	gsd *GoodsSpecsDelete
}

// Exec executes the deletion query.
func (gsdo *GoodsSpecsDeleteOne) Exec(ctx context.Context) error {
	n, err := gsdo.gsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{goodsspecs.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gsdo *GoodsSpecsDeleteOne) ExecX(ctx context.Context) {
	gsdo.gsd.ExecX(ctx)
}
