// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/shop-go/ent/orderaddress"
	"github.com/a20070322/shop-go/ent/predicate"
)

// OrderAddressUpdate is the builder for updating OrderAddress entities.
type OrderAddressUpdate struct {
	config
	hooks    []Hook
	mutation *OrderAddressMutation
}

// Where adds a new predicate for the OrderAddressUpdate builder.
func (oau *OrderAddressUpdate) Where(ps ...predicate.OrderAddress) *OrderAddressUpdate {
	oau.mutation.predicates = append(oau.mutation.predicates, ps...)
	return oau
}

// Mutation returns the OrderAddressMutation object of the builder.
func (oau *OrderAddressUpdate) Mutation() *OrderAddressMutation {
	return oau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (oau *OrderAddressUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(oau.hooks) == 0 {
		affected, err = oau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderAddressMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			oau.mutation = mutation
			affected, err = oau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(oau.hooks) - 1; i >= 0; i-- {
			mut = oau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (oau *OrderAddressUpdate) SaveX(ctx context.Context) int {
	affected, err := oau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (oau *OrderAddressUpdate) Exec(ctx context.Context) error {
	_, err := oau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oau *OrderAddressUpdate) ExecX(ctx context.Context) {
	if err := oau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oau *OrderAddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   orderaddress.Table,
			Columns: orderaddress.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderaddress.FieldID,
			},
		},
	}
	if ps := oau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, oau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderaddress.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// OrderAddressUpdateOne is the builder for updating a single OrderAddress entity.
type OrderAddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderAddressMutation
}

// Mutation returns the OrderAddressMutation object of the builder.
func (oauo *OrderAddressUpdateOne) Mutation() *OrderAddressMutation {
	return oauo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (oauo *OrderAddressUpdateOne) Select(field string, fields ...string) *OrderAddressUpdateOne {
	oauo.fields = append([]string{field}, fields...)
	return oauo
}

// Save executes the query and returns the updated OrderAddress entity.
func (oauo *OrderAddressUpdateOne) Save(ctx context.Context) (*OrderAddress, error) {
	var (
		err  error
		node *OrderAddress
	)
	if len(oauo.hooks) == 0 {
		node, err = oauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderAddressMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			oauo.mutation = mutation
			node, err = oauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(oauo.hooks) - 1; i >= 0; i-- {
			mut = oauo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oauo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (oauo *OrderAddressUpdateOne) SaveX(ctx context.Context) *OrderAddress {
	node, err := oauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (oauo *OrderAddressUpdateOne) Exec(ctx context.Context) error {
	_, err := oauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oauo *OrderAddressUpdateOne) ExecX(ctx context.Context) {
	if err := oauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oauo *OrderAddressUpdateOne) sqlSave(ctx context.Context) (_node *OrderAddress, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   orderaddress.Table,
			Columns: orderaddress.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderaddress.FieldID,
			},
		},
	}
	id, ok := oauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing OrderAddress.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := oauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderaddress.FieldID)
		for _, f := range fields {
			if !orderaddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := oauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &OrderAddress{config: oauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, oauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderaddress.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
