// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a20070322/shop-go/ent/orderinfo"
	"github.com/a20070322/shop-go/ent/predicate"
	"github.com/a20070322/shop-go/ent/wechatpay"
)

// WeChatPayQuery is the builder for querying WeChatPay entities.
type WeChatPayQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WeChatPay
	// eager-loading edges.
	withOrderInfo *OrderInfoQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WeChatPayQuery builder.
func (wcpq *WeChatPayQuery) Where(ps ...predicate.WeChatPay) *WeChatPayQuery {
	wcpq.predicates = append(wcpq.predicates, ps...)
	return wcpq
}

// Limit adds a limit step to the query.
func (wcpq *WeChatPayQuery) Limit(limit int) *WeChatPayQuery {
	wcpq.limit = &limit
	return wcpq
}

// Offset adds an offset step to the query.
func (wcpq *WeChatPayQuery) Offset(offset int) *WeChatPayQuery {
	wcpq.offset = &offset
	return wcpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wcpq *WeChatPayQuery) Unique(unique bool) *WeChatPayQuery {
	wcpq.unique = &unique
	return wcpq
}

// Order adds an order step to the query.
func (wcpq *WeChatPayQuery) Order(o ...OrderFunc) *WeChatPayQuery {
	wcpq.order = append(wcpq.order, o...)
	return wcpq
}

// QueryOrderInfo chains the current query on the "order_info" edge.
func (wcpq *WeChatPayQuery) QueryOrderInfo() *OrderInfoQuery {
	query := &OrderInfoQuery{config: wcpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wcpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wcpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wechatpay.Table, wechatpay.FieldID, selector),
			sqlgraph.To(orderinfo.Table, orderinfo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wechatpay.OrderInfoTable, wechatpay.OrderInfoColumn),
		)
		fromU = sqlgraph.SetNeighbors(wcpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WeChatPay entity from the query.
// Returns a *NotFoundError when no WeChatPay was found.
func (wcpq *WeChatPayQuery) First(ctx context.Context) (*WeChatPay, error) {
	nodes, err := wcpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wechatpay.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wcpq *WeChatPayQuery) FirstX(ctx context.Context) *WeChatPay {
	node, err := wcpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WeChatPay ID from the query.
// Returns a *NotFoundError when no WeChatPay ID was found.
func (wcpq *WeChatPayQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wcpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wechatpay.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wcpq *WeChatPayQuery) FirstIDX(ctx context.Context) int {
	id, err := wcpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WeChatPay entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one WeChatPay entity is not found.
// Returns a *NotFoundError when no WeChatPay entities are found.
func (wcpq *WeChatPayQuery) Only(ctx context.Context) (*WeChatPay, error) {
	nodes, err := wcpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wechatpay.Label}
	default:
		return nil, &NotSingularError{wechatpay.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wcpq *WeChatPayQuery) OnlyX(ctx context.Context) *WeChatPay {
	node, err := wcpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WeChatPay ID in the query.
// Returns a *NotSingularError when exactly one WeChatPay ID is not found.
// Returns a *NotFoundError when no entities are found.
func (wcpq *WeChatPayQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wcpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = &NotSingularError{wechatpay.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wcpq *WeChatPayQuery) OnlyIDX(ctx context.Context) int {
	id, err := wcpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WeChatPays.
func (wcpq *WeChatPayQuery) All(ctx context.Context) ([]*WeChatPay, error) {
	if err := wcpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wcpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wcpq *WeChatPayQuery) AllX(ctx context.Context) []*WeChatPay {
	nodes, err := wcpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WeChatPay IDs.
func (wcpq *WeChatPayQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := wcpq.Select(wechatpay.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wcpq *WeChatPayQuery) IDsX(ctx context.Context) []int {
	ids, err := wcpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wcpq *WeChatPayQuery) Count(ctx context.Context) (int, error) {
	if err := wcpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wcpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wcpq *WeChatPayQuery) CountX(ctx context.Context) int {
	count, err := wcpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wcpq *WeChatPayQuery) Exist(ctx context.Context) (bool, error) {
	if err := wcpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wcpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wcpq *WeChatPayQuery) ExistX(ctx context.Context) bool {
	exist, err := wcpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WeChatPayQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wcpq *WeChatPayQuery) Clone() *WeChatPayQuery {
	if wcpq == nil {
		return nil
	}
	return &WeChatPayQuery{
		config:        wcpq.config,
		limit:         wcpq.limit,
		offset:        wcpq.offset,
		order:         append([]OrderFunc{}, wcpq.order...),
		predicates:    append([]predicate.WeChatPay{}, wcpq.predicates...),
		withOrderInfo: wcpq.withOrderInfo.Clone(),
		// clone intermediate query.
		sql:  wcpq.sql.Clone(),
		path: wcpq.path,
	}
}

// WithOrderInfo tells the query-builder to eager-load the nodes that are connected to
// the "order_info" edge. The optional arguments are used to configure the query builder of the edge.
func (wcpq *WeChatPayQuery) WithOrderInfo(opts ...func(*OrderInfoQuery)) *WeChatPayQuery {
	query := &OrderInfoQuery{config: wcpq.config}
	for _, opt := range opts {
		opt(query)
	}
	wcpq.withOrderInfo = query
	return wcpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WeChatPay.Query().
//		GroupBy(wechatpay.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (wcpq *WeChatPayQuery) GroupBy(field string, fields ...string) *WeChatPayGroupBy {
	group := &WeChatPayGroupBy{config: wcpq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wcpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wcpq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WeChatPay.Query().
//		Select(wechatpay.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (wcpq *WeChatPayQuery) Select(field string, fields ...string) *WeChatPaySelect {
	wcpq.fields = append([]string{field}, fields...)
	return &WeChatPaySelect{WeChatPayQuery: wcpq}
}

func (wcpq *WeChatPayQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wcpq.fields {
		if !wechatpay.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wcpq.path != nil {
		prev, err := wcpq.path(ctx)
		if err != nil {
			return err
		}
		wcpq.sql = prev
	}
	return nil
}

func (wcpq *WeChatPayQuery) sqlAll(ctx context.Context) ([]*WeChatPay, error) {
	var (
		nodes       = []*WeChatPay{}
		withFKs     = wcpq.withFKs
		_spec       = wcpq.querySpec()
		loadedTypes = [1]bool{
			wcpq.withOrderInfo != nil,
		}
	)
	if wcpq.withOrderInfo != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, wechatpay.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WeChatPay{config: wcpq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, wcpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := wcpq.withOrderInfo; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*WeChatPay)
		for i := range nodes {
			if nodes[i].order_info_wechat_pay == nil {
				continue
			}
			fk := *nodes[i].order_info_wechat_pay
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(orderinfo.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "order_info_wechat_pay" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.OrderInfo = n
			}
		}
	}

	return nodes, nil
}

func (wcpq *WeChatPayQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wcpq.querySpec()
	return sqlgraph.CountNodes(ctx, wcpq.driver, _spec)
}

func (wcpq *WeChatPayQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := wcpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (wcpq *WeChatPayQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   wechatpay.Table,
			Columns: wechatpay.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wechatpay.FieldID,
			},
		},
		From:   wcpq.sql,
		Unique: true,
	}
	if unique := wcpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wcpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wechatpay.FieldID)
		for i := range fields {
			if fields[i] != wechatpay.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wcpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wcpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wcpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wcpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wcpq *WeChatPayQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wcpq.driver.Dialect())
	t1 := builder.Table(wechatpay.Table)
	selector := builder.Select(t1.Columns(wechatpay.Columns...)...).From(t1)
	if wcpq.sql != nil {
		selector = wcpq.sql
		selector.Select(selector.Columns(wechatpay.Columns...)...)
	}
	for _, p := range wcpq.predicates {
		p(selector)
	}
	for _, p := range wcpq.order {
		p(selector)
	}
	if offset := wcpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wcpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WeChatPayGroupBy is the group-by builder for WeChatPay entities.
type WeChatPayGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wcpgb *WeChatPayGroupBy) Aggregate(fns ...AggregateFunc) *WeChatPayGroupBy {
	wcpgb.fns = append(wcpgb.fns, fns...)
	return wcpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (wcpgb *WeChatPayGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wcpgb.path(ctx)
	if err != nil {
		return err
	}
	wcpgb.sql = query
	return wcpgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wcpgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wcpgb.fields) > 1 {
		return nil, errors.New("ent: WeChatPayGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wcpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) StringsX(ctx context.Context) []string {
	v, err := wcpgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wcpgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPayGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) StringX(ctx context.Context) string {
	v, err := wcpgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wcpgb.fields) > 1 {
		return nil, errors.New("ent: WeChatPayGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wcpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) IntsX(ctx context.Context) []int {
	v, err := wcpgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wcpgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPayGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) IntX(ctx context.Context) int {
	v, err := wcpgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wcpgb.fields) > 1 {
		return nil, errors.New("ent: WeChatPayGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wcpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wcpgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wcpgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPayGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wcpgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wcpgb.fields) > 1 {
		return nil, errors.New("ent: WeChatPayGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wcpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wcpgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcpgb *WeChatPayGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wcpgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPayGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wcpgb *WeChatPayGroupBy) BoolX(ctx context.Context) bool {
	v, err := wcpgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wcpgb *WeChatPayGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wcpgb.fields {
		if !wechatpay.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wcpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wcpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wcpgb *WeChatPayGroupBy) sqlQuery() *sql.Selector {
	selector := wcpgb.sql
	columns := make([]string, 0, len(wcpgb.fields)+len(wcpgb.fns))
	columns = append(columns, wcpgb.fields...)
	for _, fn := range wcpgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(wcpgb.fields...)
}

// WeChatPaySelect is the builder for selecting fields of WeChatPay entities.
type WeChatPaySelect struct {
	*WeChatPayQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (wcps *WeChatPaySelect) Scan(ctx context.Context, v interface{}) error {
	if err := wcps.prepareQuery(ctx); err != nil {
		return err
	}
	wcps.sql = wcps.WeChatPayQuery.sqlQuery(ctx)
	return wcps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wcps *WeChatPaySelect) ScanX(ctx context.Context, v interface{}) {
	if err := wcps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Strings(ctx context.Context) ([]string, error) {
	if len(wcps.fields) > 1 {
		return nil, errors.New("ent: WeChatPaySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := wcps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wcps *WeChatPaySelect) StringsX(ctx context.Context) []string {
	v, err := wcps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wcps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPaySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wcps *WeChatPaySelect) StringX(ctx context.Context) string {
	v, err := wcps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Ints(ctx context.Context) ([]int, error) {
	if len(wcps.fields) > 1 {
		return nil, errors.New("ent: WeChatPaySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := wcps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wcps *WeChatPaySelect) IntsX(ctx context.Context) []int {
	v, err := wcps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wcps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPaySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wcps *WeChatPaySelect) IntX(ctx context.Context) int {
	v, err := wcps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(wcps.fields) > 1 {
		return nil, errors.New("ent: WeChatPaySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := wcps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wcps *WeChatPaySelect) Float64sX(ctx context.Context) []float64 {
	v, err := wcps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wcps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPaySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wcps *WeChatPaySelect) Float64X(ctx context.Context) float64 {
	v, err := wcps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(wcps.fields) > 1 {
		return nil, errors.New("ent: WeChatPaySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := wcps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wcps *WeChatPaySelect) BoolsX(ctx context.Context) []bool {
	v, err := wcps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (wcps *WeChatPaySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wcps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wechatpay.Label}
	default:
		err = fmt.Errorf("ent: WeChatPaySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wcps *WeChatPaySelect) BoolX(ctx context.Context) bool {
	v, err := wcps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wcps *WeChatPaySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := wcps.sqlQuery().Query()
	if err := wcps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wcps *WeChatPaySelect) sqlQuery() sql.Querier {
	selector := wcps.sql
	selector.Select(selector.Columns(wcps.fields...)...)
	return selector
}
