// Code generated by entc, DO NOT EDIT.

package goodsspecs

import (
	"time"
)

const (
	// Label holds the string label denoting the goodsspecs type in the database.
	Label = "goods_specs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldSpecsName holds the string denoting the specs_name field in the database.
	FieldSpecsName = "specs_name"
	// EdgeGoodsSpecsOption holds the string denoting the goods_specs_option edge name in mutations.
	EdgeGoodsSpecsOption = "goods_specs_option"
	// Table holds the table name of the goodsspecs in the database.
	Table = "goods_specs"
	// GoodsSpecsOptionTable is the table the holds the goods_specs_option relation/edge.
	GoodsSpecsOptionTable = "goods_specs_options"
	// GoodsSpecsOptionInverseTable is the table name for the GoodsSpecsOption entity.
	// It exists in this package in order to avoid circular dependency with the "goodsspecsoption" package.
	GoodsSpecsOptionInverseTable = "goods_specs_options"
	// GoodsSpecsOptionColumn is the table column denoting the goods_specs_option relation/edge.
	GoodsSpecsOptionColumn = "goods_specs_goods_specs_option"
)

// Columns holds all SQL columns for goodsspecs fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldSpecsName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
